name: practice

on:
  push:
    branches:
      - main

jobs:
  build:
    name: tra
    runs-on:
      ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git branch
    - run: cat hello.txt
