name: practice

on:
  push:
    branches:
      - main

jobs:
  build:
    name: tra
    runs-on:
      ubuntu-latest
    steps:
    - uses: actions/checkout@v2


  - name: runner os
    run: echo ${{ runner.os }}
    