name: practice

on:
  push:
    branches:
      - main

jobs:
  practice:
    runs-on:
      ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: runner os
      run: echo ${{ runner.os }}
